### ISSUE TITLE
Same syntax for type level and value level expressions.

### ISSUE THREAD

**Issue by Kesanov** [HigherOrderCO/Kind#1]
It does not make much sense, to have a different syntax for values and types:
  * It introduces new syntactic noise.
  * It goes against spirit of dependent types.

E.G. There should be one notation for:
* Function, Constructor, Data arguments
* Lambda, pattern match, type level arrows

**Comment by Kesanov** [comment]
* First I would move return types of functions behind `=>`:
    ```haskell
    let not(b : Bool) => Bool
        case b
        | true  => Bool.false
        | false => Bool.true
    ```
    (The tail definition is currently very confusing! This could help it quite a bit.)

* Then data definitions could use similar notation as functions:

    ```haskell
    data Vect(A : Type, n : Nat) => Type -- is the (=> Type) really needed here?
    | cons(A : Type, n : Nat, x : A, xs : Vect(A, n)) => Vect(A, Nat.succ(n))
    | nil(A : Type) => Vect(A, Nat.zero)
    ```

**Comment by Kesanov** [comment]
Is there any reason to not use the same syntax both for `->` and `=>` ?
Do we need lambdas in type definitions?

**Comment by Josef-Vonasek** [comment]
I would rename `case` to `when` or `match`

**Comment by VictorTaelin** [comment]
You're mistaken that there is a distinction here. `->` and `=>` are two very different things, one is `forall` (the **type** of a lambda) and the other is a lambda itself. The distinction is necessary for the same reason we need that distinction on the pure Calculus of Constructions. 

There is no distinct syntax between value and type levels because everything is at the same level, i.e., Formality is a Pure Type System. It just happens that `->` (forall) and `=>` (lambda) represent two different things, but they coexist in the same level, you can store an array of lambdas, you can store an array of foralls, and so on.

The `=> Type` there is indeed useless given that we only have one `Type`, but avoiding it would require parsing those things independently, which would need more code (since, right now, it just reuses the syntax for lambdas). That'd be fine, but another problem is eventually we'll probably have more than a single `Type` (because of paradoxes), in which case it'll be necessary.

Functions do not have annotated return types! Formality is similar to Morte-lang in that sense, only arguments are annotated. `case` expressions have a return type, though, as is required by dependent pattern matching. 

The syntax for datatypes is:

```
data name type
| ctor_0 type
| ctor_1 type
```

Notice that `=>` is not part of the `data` syntax; what you see is just functions! For example, this is equivalent to the definition above:

```
let v_typ (A : Type, n : Nat) -> Type
let c_typ (A : Type, n : Nat, x : A, xs : Vect(A, n)) => Vect(A, Nat.succ(n))
let n_typ (A : Type) => Vect(A, Nat.zero)

data Vect v_typ
| cons c_typ
| nil n_typ
```

Similarly, the syntax for `let` is just: `let name value body`. When you see:

```
let id(x : Nat) =>
  x

id(Nat.zero)
```

This actually parses as:

```
let ... name ... value            ... body
let ...  id  ... ((x : Nat) => x) ... id(Nat.zero)
```

This is the syntax for pattern matching:

```
case a
| ctor_0(field_0, field_1) => body_0
| ctor_1(field_0, field_1) => body_1
: (index_0, index_1) => return_type
```

Notice that, here, `(field_0, field_1)` **is** part of the syntax, because there are no type annotations on those, so we can't reuse the syntax for lambdas, which is fully annotated.

**Comment by VictorTaelin** [comment]
For a reason we can't move the "return type" to where you suggest, see the definition of `head`:

```
let head(A : Type, n : Nat, vect : Vect(A, Nat.succ(n))) =>
    case vect
    | cons(A, n, x, xs) => x
    | nil(A)            => Unit.void
    : (A, n) => case n
        | succ(m) => A
        | zero    => Unit
        : Type
```

It has two "return types". Because the "return type" is actually part of `case`, not the function. Functions are just lambdas with annotated arguments: `(a : A, b : B, ...) => t`.

**Comment by Kesanov** [comment]
@MaiaVictor Could you explain the purpose of `index_0` and `index_1`? 

Int the `head` example you redefine `A` and `n`, which are already known!

**Comment by VictorTaelin** [comment]
They are not! On total pattern matching, each branch has different indexes, and, thus, a different return type. As such, you must specify the return type as a function from indexes to a Type. The syntax:

```
case a
| ctor_0(field_0, field_1) => body_0
| ctor_1(field_0, field_1) => body_1
: (index_0, index_1) => return_type
```

Is equivalent to Coq's:

```
match a in Type index_0 index_1 return return_type with
| ctor_0 field_0 field_1 => body_0
| ctor_1 field_0 field_1 => body_1
```

There are only minor differences. For a better explanation on why those are necessary, I suggest Coq's [extended pattern matching](https://coq.inria.fr/refman/addendum/extended-pattern-matching.html) article.

**Comment by Kesanov** [comment]
I think you should really keep the `Type` in there and perhaps move it to top:

```haskell
case a
: Type  (index_0, index_1) => body_type
| ctor_0(field_0, field_1) => body_0
| ctor_1(field_0, field_1) => body_1
```

**Comment by VictorTaelin** [comment]
Moved the type to top on ce239ccf46286463ddcb0109dd13c5f02dcce237.
