### ISSUE TITLE
Improve error message for "for loop"

### ISSUE THREAD

**Issue by MaisaMilena** [HigherOrderCO/Kind#152]
Following the code:
```
Example(xs: List<Nat>): List<Nat>
  let ordained = xs
  for x in xs with ordered:
    ordained = sort(ordained)
  ordained 
```
Get an error message of `Expected letter` in the code below it, but it doesn't explain the error.

**Correct code**
Remove `ordained = `. The body of `for` already returns changes to the variable `ordained `.
```
Example(xs: List<Nat>): List<Nat>
  let ordained = xs
  for x in xs with ordained:
    sort(ordained)
  ordained 
```

**Solution**
Improve error message for when the body of `for loop` contains the variable used with `with`.

**Comment by rigille** [comment]
since https://github.com/uwu-tech/Kind/pull/202 the error message is a bit better. typechecking
```
Example(xs: List<Nat>): List<Nat>
  let ordered = xs
  for x in xs with ordered:
    ordered = List.reverse!(ordered)
    ordered 
```
results in
<pre>Expected a term. Inside term:
   1 | Example(xs: List&lt;Nat&gt;): List&lt;Nat&gt;
   2 |   let ordered = xs
   3 |   for x in xs with ordered:
   4 |     ordered = List.reverse!(ordered)
   5 |     ordered 
   6 | <span style="background-color:#CC0000"><font color="#D3D7CF">_ </font></span>
       ^
</pre>
