### ISSUE TITLE
The default case messed up the clause checker.

### ISSUE THREAD

**Issue by caotic123** [HigherOrderCO/Kind#194]
# Expected Behavior

```
Example.bugs.bug0(x : List<Bool>) : List<Bool>
  case x {
      true : x.head
  } default x
```

` Example.bugs.bug0` must not be typeable, first :
    - true is not a clause of a List<A>
    - x.head is a Bool, however, the function asks for a List<Bool>

# Current behavior
It actually type checks.

# How to reproduce 
Just run the kind type checker on that file `Kind Example.bugs.bug0`

**Comment by MaisaMilena** [comment]
That's because if a constructor doesn't exist (the right constructors for this `case` are `nil` and `cons`), it's ignored and only the `default` it's valid. `x` is a List so it type checks.
```
Example.bugs.bug0(x : List(Bool)) : List(Bool)
  case x {
    cons: x.head
    true : x.head
  } default x
``` 
This example gives an error of "type mismatch" in the `cons: x.head` as expected.

The solution for this problem would be to only accept valid constructors inside the `case`.

**Comment by caotic123** [comment]
Sure, 

> That's because if a constructor doesn't exist (the right constructors for this `case` are `nil` and `cons`), it's ignored and only the `default` it's valid. `x` is a List so it type checks.
> 
> ```
> Example.bugs.bug0(x : List(Bool)) : List(Bool)
>   case x {
>     cons: x.head
>     true : x.head
>   } default x
> ```
> 
> This example gives an error of "type mismatch" in the `cons: x.head` as expected.
> 
> The solution for this problem would be to only accept valid constructors inside the `case`.

Sure, however, the type checker is supposed to check all terms of the case, even if is not reachable.
In that way, ```
 case x {
      true : x.head
  }
```, must not be typeable, once x.head is undefined.

**Comment by VictorTaelin** [comment]
Exactly. This isn't actually a bug (I've been mistaken when I told you it was). @MaisaMilena is correct. The problem is, we can not apply her suggestion and accept only valid constructors, because we don't always know what are the constructors of a datatype. For example, [here](https://github.com/uwu-tech/Kind/blob/master/blog/1-beyond-inductive-datatypes.md) I present datatypes with conditional constructors that aren't always known and depende of computations. Regardless, it would still be a good idea to show a warning when the user writes cases for constructors that are missing.
