### ISSUE TITLE
using Parser blocks as local variables fails in compilation

### ISSUE THREAD

**Issue by rigille** [HigherOrderCO/Kind#205]
when Kind is compiled to FormCore, it inlines certain definitions, such as Parser.bind and Parser.pure. because of that, if you use "let" to define a parser, such as:

```
Test: _
  let parser =
    Parser {
      get k = Parser.text("oi")
      return k
    }
  parser(Parser.State.new(none, "", 0, 0, "oi oi"))
```
it will fail to compile, because the `Parser { … }` block will become a lambda, and FormCore can't infer the type of lambdas in the body of a let expression.

**Comment by VictorTaelin** [comment]
That's because the Parser monadic functions are inlined when compiled to FormCore, and, thus, it becomes a lambda. On FormCore, `let` with a lambda results in a "can't infer" error. We can solve this by not inlining the parser, but that would cause errors on the JS and Scheme backend, since Kind's parser has some mutual recursive definitions that can't be sorted by dependency order and thus will be seen as undefined variables on either back-ends. We can prevent that by wrapping all top-level definitions around a lambda, but that will cause re-computation of top-level constants. We could memoize, though. That will allow Parser to work, but will probably result in some loss of performance. Alternatively, perhaps we can make the inliner smarter to avoid inlining inside the expression of a let?

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
