### ISSUE TITLE
Trying to return a forall is ambiguous

### ISSUE THREAD

**Issue by rigille** [HigherOrderCO/Kind#220]
as of `1.0.59` the syntax can't distinguish
```
Associative<A: Type>(op: A -> A -> A): Type
  (a: A, b: A, c: A) -> Equal<A>(op(op(a, b), c), op(a, op(b, c)))
```
from
```
Associative<A: Type>(op: A -> A -> A): Type -> (a: A, b: A, c: A) -> Equal<A>(op(op(a, b), c), op(a, op(b, c)))
```
and the parser chooses the later by default. there's a workaround if you do
```
Associative<A: Type>(op: A -> A -> A): Type
  def ret = (a: A, b: A, c: A) -> Equal<A>(op(op(a, b), c), op(a, op(b, c)))
  ret
```
but it would be better if we had some syntax to explicitly terminate the return type of the top-level definition.

**Comment by VictorTaelin** [comment]
I don't like the idea of a syntax to explicitly terminate the return type... there are many other places where the same issue would happen (like, after a `let` ?). Are you sure it is parsed as:

```
Associative<A: Type>(op: A -> A -> A): Type -> (a: A, b: A, c: A) -> Equal<A>(op(op(a, b), c), op(a, op(b, c)))
```

It makes no sense since there isn't an arrow after `Type`. Perhaps it is parsed as something else?

For now, you can use a parenthesis to fix it:

```
Associative<A: Type>(op: A -> A -> A): Type
  ((a: A, b: A, c: A) -> Equal<A>(op(op(a, b), c), op(a, op(b, c))))
```

But I'd like to understand what is going on with the `->`

**Comment by racs4** [comment]
With the change made in 23fce8d7dd2512f10c2240db7ed6d8a0e0583bd0, this is no more a problem @rigille
