### ISSUE TITLE
Any plans for type inference?

### ISSUE THREAD

**Issue by lostmsu** [HigherOrderCO/Kind#3]
Omnipresent type signatures make example code hard to read.

**Comment by VictorTaelin** [comment]
I think Formality should be kept as simple as it possibly can, then tools should be added on top of it. I'm not very fond of inference in particular, I think proof search should replace it when it comes to writing code. On readability, bidirectional-type checking could improve it, but so could a smart editor capable of hiding/expanding certain expressions, and, since Formality is intended to be used mainly on Ethereum's upcoming browser, we can have that. But I'm always open to ideas. We'll see...
