### ISSUE TITLE
Ability to prove false theorems

### ISSUE THREAD

**Issue by Ekdohibs** [HigherOrderCO/Kind#317]
With the following code, I can prove the false theorem `Empty`:
```
false_1(n: Nat): Empty
  false_1(n)
```

This is because there is no termination checking. (Of course, no actual program will look like this, but such a pattern could appear hidden inside a complex proof).

Besides, I can also use the following code to prove `Empty`:
```
type negind {
  new(f: Not(negind))
}

ni(n: negind): Empty
  case n {
    new: n.f(n)
  }

false_2: Empty
  ni(negind.new(ni))
```
This time, the problem is that strict positivity is not checked in inductive datatypes.

**Comment by rigille** [comment]
hey @Ekdohibs
indeed it's possible to prove false theorems in kind and i've almost run into problems once because of divisions by zero. however we want to allow these programs to keep kind usable as a general purpose language. expressiveness is the default and consistency would be opt-in, with likely many different consistency checkers to choose from. unfortunately no one got around to write a consistency checker yet. there are some ideas regarding this [here](https://github.com/Kindelia/Kind/blob/master/CONTRIBUTE.md#add-a-consistency-checker)
