### ISSUE TITLE
[Documentation] IsEven 5 is possible because of float as Number

### ISSUE THREAD

**Issue by LoPoHa** [HigherOrderCO/Kind#40]
Like the title says:

You can construct `IsEven(5)` with `make_even(2.5)` since you switched from integer to floats for Number.

Changing from Number to Nat does fix this issue.

**Comment by johnchandlerburnham** [comment]
Thanks for the catch! We're working on changing our native number type back to unsigned integers, but Javascript's lack of u64 support is proving a bit of a stumbling block.

The current plan is to change the FM-Net model to have numeric primitives that align more closely with WASM, as outlined here: https://github.com/moonad/Formality/pull/38

But since `fm-net.js` relies heavily on the `Net` being an array of numbers, it seems like the easiest way to implement this is by just doing the whole net reduction in WASM.

I've done some work on this with @michaelforney here: https://github.com/michaelforney/Formality-C/pull/1

**Comment by VictorTaelin** [comment]
Good point! Changed it to use `Nat` instead.
