### ISSUE TITLE
Datatype definition order is significant

### ISSUE THREAD

**Issue by courajs** [HigherOrderCO/Kind#51]
The following typechecks and runs fine:
```haskell
T Thing
| thing

main: Thing
  case thing
  | thing => thing
```

But this does not:
```haskell
main: Thing
  case thing
  | thing => thing

T Thing
| thing
```

It gives the following parse error (the space between "case" and "thing" on line 2 is highlighted):
```
tmp$ fm -t
[PARSE-ERROR]
Couldn't find the ADT for this pattern-match.
Make sure the cases have the correct name and order.

I noticed the problem on line 2, col 7, file main.fm:

   1| main: Thing
   2|   case thing
   3|   | thing => thing
   4|
   5| T Thing
   6| | thing
```

**Comment by VictorTaelin** [comment]
Good catch. That is one of the limitations of the parser. Since it has no type information, it requires the datatype to be already parsed when you use a `case` expression. There are two good alternatives:

1. Do the parsing in two steps. On the first one, collect the structure of the cases and all datatypes. On the second one, use the datatype information to compile to fm-core properly.

2. Change the `case` syntax so that it doesn't need datatype information. It would go from this:

    ```haskell
    case vector
    | cons => vector.head
    | nil => 0n
    : Nat
    ```

    To this:

    ```haskell
    case vector
    | cons(len; head, tail) => head
    | nil => 0n
    : (len, vector) => Nat
    ```

I personally think the later is way uglier, I like the simplicity of Formality's case expressions. Doing parsing in two steps is the way to go. When rewriting the language in itself, we should have that in mind. @johnchandlerburnham

**Comment by VictorTaelin** [comment]
Formality was refactored, solving this issue! We now don't rely on type information for parsing anymore, using `;` instead. This allows us to pattern-match on a datatype before declaring it, at the cost of a slightly more verbose syntax.
