### ISSUE TITLE
Improvement in equality needed

### ISSUE THREAD

**Issue by gabriel-barrett** [HigherOrderCO/Kind#54]
Because types are corecursively defined, to check whether those types are equal, we cannot just normalize them and check whether their normal forms are definitionally equal. Rather, we attempt to reduce redexes in all possible orders, branching and performing a breadth-first search. However, the problem with this is that type checking some code like
```
nat.test0: The(Nat, 100n)
  the(_ add(50n, 50n))
```
is incredibly (exponentially) slow, since it will try to reduce `add(50n, 50n)` in all possible orders. A better solution would be to normalize the term before.

How should we prevent the type checker from doing the slow search when it isn't needed? As a possible direction to the solution of this problem I stress that while types are corecursively defined, terms are recursively defined, so that we might need different strategies depending on whether we are dealing with a term or a type.

**Comment by VictorTaelin** [comment]
One might think we could just check equality as such:

1. If both terms are identical, return true;

2. Otherwise, take the WHNF of them;

    - If heads differ, return false. 

    - Otherwise, recurse.

This allows to unroll both sides layer by layer until they coincide perfectly, and then stop. But this won't always work. For example, consider the code below:

```
Id(x : Type) : Type
  x

T Unit
| unit

T One<A>
| one

main : One(Id(Unit))
  one(Unit;)
```

To check this term, the type-checker must decide if `One(Unit)` and `One(Id(Unit))` are equal. It will proceed as follows:

```
is_equal:
- One(Unit)
- One(Id(Unit))

is_equal:
- ${s} (P: One(Unit) -> Type; one : P(one)) -> P(s)
- ${s} (P: One(Id(Unit)) -> Type; one : P(one)) -> P(s)

is_equal:
- (P: One(Unit) -> Type; one : P(one)) -> P(s)
- (P: One(Id(Unit)) -> Type; one : P(one)) -> P(s)

is_equal:
- One(Unit) -> Type
- One(Id(Unit)) -> Type

is_equal:
- One(Unit)
- One(Id(Unit))
```

Notice it loops infinitely, without ever making both sides identical. The problem is that taking the WHNF applies the leftmost functions, which, in this case, is `One`, but, in order to make both sides identical, what we really needed was to apply `Id`, so we'd obtain `One(Unit) == One(Unit)`. This forces us to explore the space of possible reduction orders, which can be exponential if you're trying to type-check recursive functions applied to constants. 

I don't really agree with the type/term distinction since it doesn't really exist, Formality terms and types are defined the same. There is nothing preventing a user to define a regular term that performs the same recursion of the type I just presented. The solution would be some way to guide the compiler into doing the right reductions, but I'm not sure how that could be done. In the worst case, it could ask the programmer for hints.

This paper may be relevant: https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.4.2276&rep=rep1&type=pdf

**Comment by effectfully** [comment]
> Because types are corecursively defined, to check whether those types are equal, we cannot just normalize them and check whether their normal forms are definitionally equal.

I'd say that the problem is in the "types are corecursively defined" part and definitional equality being hard is just a symptom. How inherent equirecursion is? Looking at

```
Nat : Type
  ${self}
  ( P    : Nat -> Type
  , succ : (r : Nat, i : P(r)) -> P(succ(r))
  , zero : P(zero)
  ) -> P(self)
```

I kind of feel that it might be possible to simply add Haskell-style `newtype`s to the language and write

```
newtype Nat = MkNat { unNat :: NatBody }

NatBody : Type
  ${self}
  ( P    : Nat -> Type
  , succ : (r : Nat, i : P(r)) -> P(succ(r))
  , zero : P(zero)
  ) -> P(self)
```

this makes `Nat` a stuck/neutral term that doesn't reduce indefinitely, i.e. equirecursion is hidden behind a `newtype` wall which practically makes it isorecursion. Pretty much like you can't have impredicative polymorphism in Haskell, but can hide polymorphism behind a `newtype` wrapper, which allows to easily circumvent the problem.

I'm not sure if it's going to work, because I'm not very familiar with the system and it might be the case that some simple wrapping-unwrapping wouldn't help to define `zero`, `succ` and `nat_ind`. But if it's possible to implement `zero` etc, then I'd say this is the way to go.

Of course there is then a question of how exactly to add newtypes to the language, but it's certainly solvable and much easier than checking infinite types for equality (simplicity of the theory is not the only thing that is important (and simplicity is orthogonal to minimalism anyway), simplicity of the implementation is also very important, because that implementation is going to handle goods of other people, so the more trustable it is, the better, and simplicity makes things more trustable).

**Comment by effectfully** [comment]
[Seems to work](https://gist.github.com/effectfully/afaecc90c1f4d4e617759917cc9c4d68) (it's a fake version of Formality in Agda with what is essentially the `newtype` wrapper described above). Although the `inst n (fromNat n)` part probably indicates that the typing rules need to be tweaked to account for wrapping-unwrapping.

**Comment by johnchandlerburnham** [comment]
We might not even need to add a separate `newtype` wrapper to do this.

Here are the Formality definitions for non-inductive Scott Nat (for disambiguation) and then the definition for induction INat (corresponding to what you have):

```
Nat : Type
  ${self}
  ( P: (wit: Nat) -> Type;
    zero: P(zero),
    succ: (pred: Nat) -> P(succ(pred))
  ) -> P(self)

zero : Nat
  new(Nat) (P; zero, succ) => zero

succ(pred : Nat) : Nat
  new(Nat) (P; zero, succ) => succ(pred)

INat : Type
  ${self}
  ( P     : INat -> Type;
    izero : P(izero),
    isucc : (r : INat; i : P(r)) -> P(isucc(r))
  ) -> P(self)

isucc(r : INat) : INat
  new(INat) (P; izero, isucc) =>
  isucc(r; use(r)(P; izero, isucc))

izero : INat
  new(INat) (P; izero, isucc) => izero
```

With a `newtype` wrapper, I think that should look like

```
-- mixing syntaxes with psuedo-Haskell
newtype INat = MkINat { unINat :: INatBody }

INatBody : Type
  ${self}
  ( P     : INat -> Type;
    izero : P(izero),
    isucc : (r : INat; i : P(r)) -> P(isucc(r))
  ) -> P(self)

isucc(r : INat) : INat
  MkINat((P; izero, isucc) => isucc(r; unINat(r)(P; izero, isucc))

izero : INat
  MkINat((P; izero, isucc) => izero)
```

In other words, `MkINat` and `unINat` are precisely `new` and `use`. The only difference is in how `${self}` (or `Slf "self" t`in the AST) is typed, since with the newtype there's a level of indirection.

Since `new` and `use` are already abstracted away from the user in the `ADT` and `case` syntax sugars, this suggest a modification to the Formality type system where we disallow naked equirecursion in types and require the use of `Slf`:

```
Inf : Type
  Nat -> Inf

-- becomes

 Inf : Type
   ${self} Nat -> Inf

-- which would correspond to Haskell
-- data Inf = MkInf { unInf :: Nat -> Inf }

unroll : Inf -> (Nat -> Inf)
  use(Inf)

roll : (Nat -> Inf) -> Inf
  new(Inf)
```

I think this will probably work, but I have some further questions:

1. Would this require adding a new primitive to witness the `roll . unroll ~ unroll . roll` isomorphism? Or can that witness already be generated at the user-level from the isorecursive system outlined above. The following witness for non-parameterized self-types already type-checks:

```
wit1(P: Type, x : ${self} P) : (new(${self} P)(use(x))) == x
  equal(${self} P; x;)

wit2(P : Type, x : P) : use((new(${self} P)(x))) == x
  equal(P; x;)
```

But I cannot figure out how to write  `P` when it is a proposition on `self`.

2. We have to still be able to strip out `new/use` when we compile. So the runtime representation of e.g. `zero` will still just be the lambda `(zero, succ) => zero`.

3. Is there any other use case for being able to define infinite types that we're overlooking? I suspect not, but want to makes sure.

**Comment by VictorTaelin** [comment]
After reading this, I think John's suggestion is a neat way to fit the `newtype` idea without having a new constructor, but, that that doesn't help with the problem posed at all. I'll stress that Formality's type-checker must check if two arbitrary, possibly non-terminating λ-terms are identical. The problem at hands is how to do that more efficiently.

Note this has nothing to do with self-types, equirecursion, isorecursion, not types at all. What you're doing is implementing a fast algorithm for very specific cases (when the terms are the type of a datatype), but this is **not** the posed problem, not it is interesting nor relevant (Formality is already very fast in those cases btw)! In order to make progress in the right direction, let me please re-define the issue terms of the λ-calculus. We're looking for the following algorithm that:

> Given two arbitrary untyped λ-calculus terms, find two reduction paths (that is, a sequence of redexes to be applied) that makes both λ-terms identical.

This is the problem I'm interested in solving. I hope it is clear now.

**Comment by effectfully** [comment]
@johnchandlerburnham 

> The only difference is in how `${self}` (or `Slf "self" tin` the AST) is typed, since with the newtype there's a level of indirection.

I can imagine typing rules along the lines of

```
Γ , x : D ⊢ T : *     D wraps (ι x. T)
--------------------------------------
    Γ ⊢ (ι x. T) : *

Γ ⊢ t : D    D wraps (ι x. T)
-----------------------------
Γ ⊢ unwrap t : [t / x]T

Γ ⊢ t : [wrap t / x]T    Γ ⊢ (ι x. T) : *    D wraps (ι x. T)
-------------------------------------------------------------
           Γ ⊢ wrap t : D
```

where `D wraps Z` is a judgement for "`D` is a wrapped version of `Z`".

> Would this require adding a new primitive to witness the `roll . unroll ~ unroll . roll` isomorphism?

`roll . unroll` and `unroll . roll` are of different types, right? Both of them should beta-reduce to `id`, though, so it's just a couple more rules for the normalizer.

> We have to still be able to strip out `new/use` when we compile. So the runtime representation of e.g. `zero` will still just be the lambda `(zero, succ) => zero`.

Sure, a `newtype` is supposed to be a zero-cost abstraction.

> Is there any other use case for being able to define infinite types that we're overlooking? I suspect not, but want to makes sure.

Not aware of any. Even when I want types like `D ≅ (D -> D)`, I still like to control how they unfold.

@MaiaVictor 

> I'll stress that Formality's type-checker must check if two arbitrary, possibly non-terminating λ-terms are identical.

Apart from the equirecursion, why do you *need* to do something with non-terminating terms at the type level (as opposed to just allowing such terms for the sake of not having a restrictive system)? 

Anyway, I agree, fast equality checks are essential and from a practical perspective a term that takes ages to compute doesn't differ from a non-terminating one. And it's not unique to Formality, every other language, not even necessarily a dependently typed one, wants a fast equality check. Which is why people have been researching algorithmic equality. I'm not aware of any bleeding edge results, but for example the "3. Algorithmic Equality" section of [On irrelevance and algorithmic equality in predicative type theory](https://arxiv.org/abs/1203.4716) describes an algorithm similar to the one that you've outlined. I completely agree that spotting that `f x` and `f (id x)` are the equal without descending into `f` would be a very important optimization, but speaking of types:

1. whatever you do, you can't outperform type checking isorecursive types with equirecursive ones, speaking generally. E.g. your example `is_equal (One Unit) (One (Id Unit))` immediately reduces to `is_equal Unit (Id Unit)`, because with isorecursive types `One` is neutral and hence the only way these two types can be equal is if their arguments are also equal
2. Imagine you can check infinite things for equality (people who write supercompilers routinely fold infinite structures into finite ones and it's possible to apply those techniques here). Questions arise:

- which equality? Denotationally, `foldl (+) 0 [1..]` is the same thing as `last [0..]`, but operationally the latter will not exhaust all available memory unlike the former

- in your example the corecursive call is productive (i.e. you have guarded corecursion there, i.e. some data gets pushed "to the outside" unlike in the `foldl` and `last` examples). It's indeed possible in some cases to check equality of such infinite trees, but this is quite an advanced feature and if you remove the equirecursion, which requires such checks, other use cases are not as compelling, I believe. Doing the common thing well is much more important than doing common and uncommon things only fine (and having exponential blowup whenever two terms need to be checked for equality is hardly fine). But anyway, the reduce-to-whnf-check-proceed algorithm can be extended to handle such use cases: when you reduce `is_equal (One Unit) (One (Id Unit))` and reach `is_equal (One Unit) (One (Id Unit))`, i.e. the original expression, you get two cyclic finite graphs (one is formed by the reduction path of `One Unit` and the other one is formed by the reduction path of `One (Id Unit)`), and those graphs are of the same shape, so we conclude that they are the same without ever reducing `Id Unit` (basically we folded an infinite tree into a finite cyclic graph and this is exactly what supercompilers people do (well, the simplest thing that they do)). But this brings us to another point:

- by identifying a data type with its encoding, you're essentially enabling structural typing. Is it the case that in this system `One Bool` is supposed to be equal to `One Nat`? Their reduction paths are the same cyclic graph, because `One` is phantom, i.e. never uses its parameter. If they are indeed supposed to be equal, then the encoding breaks abstraction that the user would expect to be preserved (I certainly do not want the type checker to allow using `newtype Usd = Usd Int` where `newtype Eur = Eur Int` is expected). Probably you don't want them to be equal either, but how are you going to discriminate between them then (given that `One` is essentially a function and there does exist such a function `f` that `f Bool == f Nat`, so you can't just return `false` on the basis of the arguments being different)?

**UPDATED**

**Comment by johnchandlerburnham** [comment]
@MaiaVictor 

>Given two arbitrary untyped λ-calculus terms, find two reduction paths (that is, a sequence of redexes to be applied) that makes both λ-terms identical.

Let's call this procedure `join`. If we fix on of the arguments to `join`, call it `P`, then since `(x) => join(P,x)` is nontrivial, `join` is undecidable by [Rice's Theorem](https://en.wikipedia.org/wiki/Rice%27s_theorem). So at best we're looking for a semidecision procedure

Consider the complementary problem, `separate`:

>Given two arbitrary untyped λ-calculus terms, find two reduction paths (that is, a sequence of redexes to be applied) that makes both λ-terms distinct.

At most one of `join` and `separate` are semidecidable, since (as complements) if both were semidecidable they would both be decidable.

A semidecision procedure for `separate` in the λ-calculus is given on page 19 of [Gerard Huet's "Analysis of Bohm's Theorem"](https://www.sciencedirect.com/science/article/pii/030439759390087A), via the Bohm-out algorithm.

The distinction between isorecursion and equirecursion is relevant because Formality has unrestricted recursive types, via the `Ref` constructor. This means that there is an additional way to build infinite terms (beyond the usual fixpoint combinators):

```
Inf1 : Type
  Nat -> Inf1

Inf2 : Type
   Nat ->Inf2

Inf3_body(X : Nat) : Type
   X -> Inf3_body

Inf3 : Type
   Inf3_body(Nat) 
```

Athough these terms are all definitionally the same, representing an infinite tree of `Nat -> Nat -> ...` the semidecision proceure for `separate` will not terminate on it (and neither would BFS `equal` algorithm in `core.ts`, which we could consider as a weak `join`). 

To solve this, Gabriel and I have implemented the encoding of recursive terms as first order canonical forms (from this paper: http://gallium.inria.fr/~fpottier/publis/gauthier-fpottier-icfp04.pdf), and what appears to be a more expressive equality: https://github.com/moonad/Formality-Haskell/blob/gb/equality/src/FirstOrder.hs

This seems to work for a lot of cases, but based on [this paper](http://ps.informatik.uni-tuebingen.de/research/functors/equirecursion-fomega-popl16.pdf) it seems like we'll run into trouble (supposedly of the "decades old unsolved research problem" variety) when try to recurse on higher-kinded terms like e.g. `Vector : Type -> Nat -> Type` . In other words, when we mix type-level applications and equirecursion.

The nice thing about isorecursion is that it basically merges recursive types into the existing problem of finding redex paths (either `join`/`separate`), because isorecurive `roll/unroll` can be treated like applications.

---
@effectfully 

To solve the problem of abstraction breaking for phantom type parameters, maybe we could use type indices?

```
-- T One<A>
-- | one

One(A : Type) : Type
  ${self} 
  ( P: (wit: One(A)) -> Type;
    one: P(one(A;))
  ) -> P(self) :: Type

one(A : Type;) : One(A)
  new(One(A)) (P; one) => one :: One(A)

--T OneI (A : Type)
--| oneI(A : Type) : OneI(A)

OneI(A: Type)
  ${self}
  ( P : (A: Type, wit: OneI(A)) -> Type;
    oneI : (A: Type) -> P(A, oneI(A))
  ) -> P(A, self) :: Type

oneI(A: Type) : OneI(A)
  new(OneI(A))
  (P; oneI) => oneI(A) :: OneI(A)
```

**Comment by VictorTaelin** [comment]
>  Apart from the equirecursion, why do you need to do something with non-terminating terms at the type level (as opposed to just allowing such terms for the sake of not having a restrictive system)?

That's not the point. We do absolutely need to check the equality between 2 arbitrary λ-terms, because that is literally the definition of the problem at hands. Formality, by design, doesn't have native datatypes, so it must deal with λ-encodings. The type checker has a λ-term in one side, a λ-term on the other, it must check if those are equal, so it needs an algorithm that does that. Simple as that. Am I missing something obvious here?

What you seem to be trying to do is to restrict Formality so we can have faster equality in some cases, but seems like those cases are getting suspiciously close to Agda! The reason Agda's type-checker is fast is that it refuses to reduce inside lambdas when not guarded by a native constructor. That is nice, but not sufficient for us, since it is incapable of dealing with equality of recursive lambdas properly. For example, the program below:

```agda
{-# OPTIONS --type-in-type --no-termination-check #-}

Nat : Set
Nat = (P : Set) -> (S : Nat -> P) -> (Z : P) -> P

succ : Nat -> Nat
succ n P s z = s n

zero : Nat
zero P s z = z
```

Causes Agda to crash hopelessly. And it is the simplest recursive λ-encoding you can write down, it doesn't even involve self-types or induction. For the same reason, it can't deal with function equality properly. For example, the program below:

```agda
data Equal (A : Set) (a : A) : (b : A) -> Set where
  equal : Equal A a a

data Nat : Set where
  zero : Nat
  succ : Nat -> Nat

f : Nat -> Nat
f zero        = zero 
f (succ pred) = succ (succ pred)

g : Nat -> Nat
g zero        = zero
g (succ pred) = f (succ pred)

main : Equal (Nat -> Nat) f g
main = equal
```

Doesn't involve λ-encodings and doesn't crash Agda, but still fails to type-check as it refuses to reduce inside functions:

```
f x != g x of type Nat when checking that the expression equal has type Equal (Nat → Nat) f g
```

The Formality equivalent doesn't have that problem:

```javascript
| zero
| succ(pred: Nat)

f(n : Nat) : Nat
  case n
  | zero => zero
  | succ => succ(succ(f(n.pred)))

g(n : Nat) : Nat
  case n
  | zero => zero
  | succ => f(succ(n.pred))
 
main : Equal(Nat -> Nat, f, g)
  equal(__)
```

It type-checks instantly:

```javascript
Equal((:Nat) -> Nat, f, g) ✔
```

Note this is **not** extensional equality, it is just that Formality is not afraid of reducing inside lambdas in order to find that `f` and `g` both unroll to a same common term. Other things like fusible algorithms that must break down constructor into smaller pieces would probably fail under that approach. For example:

```javascript
foo(n:Nat, b:Bool) : Nat
  ${self} (P; succ; zero)
  case b 
  | true => succ(n)
  | zero => zero
```

Isn't even expressive in Agda, so we'd ultimately still need to fallback to my more algorithm in those cases. Note that I'm not saying you can't improve the performance there, of course you can; for example, in the worst case we could simply identify the Agda subset of Formality and use it. But the problem is: what about those terms that Agda can't deal with? The point of this issue was to look for better ways to compare arbitrary λ-terms, since my algorithm is quite naive. And yes, of course this procedure is undecidable, and slower than more well-behaved cases. That doesn't mean we can't improve my algorithm. Am I making sense?

**Comment by effectfully** [comment]
@johnchandlerburnham 

> To solve the problem of abstraction breaking for phantom type parameters, maybe we could use type indices?

Clever! Looking at

```
OneI(A: Type)
  ${self}
  ( P : (A: Type, wit: OneI(A)) -> Type;
    oneI : (A: Type) -> P(A, oneI(A))
  ) -> P(A, self) :: Type
```

I think yes, it works: `P` is a variable => `P` is neutral => `A /= B` implies `P A /= P B` => `A /= B` implies `OneI A /= OneI B`.

@MaiaVictor 

> What you seem to be trying to do is to restrict Formality so we can have faster equality in some cases, but seems like those cases are getting suspiciously close to Agda!

I'm not trying to restrict Formality. Absolutely do allow non-terminating terms (at least because there is no sensible way not to allow them without also disallowing lots of valid terminating ones). Do research a way to get fast equality checks, so that `equal : Equal (expensive_f n) (expensive_f (id n))` type checks instantly, which will also give you the ability to check **some** infinite terms for equality as a side-effect.

What I'm saying is that I'm not convinced that you need to explicitly target infinite terms, because I do not see what kinds of infinite terms you actually need. Yes it's true that fast equality check will handle some of such terms, but if you aim for handling different ones and those turn out to be replaceable by finite ones *without reducing the expressiveness of the system while at the same time improving performance of the type checker*, then just tweaking a system a bit will save you a lot of headache.

It might be possible that you can replace equirecursion with isorecursion without reducing the expressiveness of the system. That would give you a simpler system overall, as well as a faster type checker. It might be not possible in Formality. I'm not insisting on anything, I'm only suggesting to consider the possibility of making the system simpler and faster, provided that doesn't impede usability in any way.

I'm also describing what problems identifying things with their encodings might cause. Is it the case that with `One` defined as a parameterized type (as opposed to an indexed one) `One Bool` and `One Nat` are the same?

> We do absolutely need to check the equality between 2 arbitrary λ-terms, because that is literally the definition of the problem at hands. Formality, by design, doesn't have native datatypes, so it must deal with λ-encodings. The type checker has a λ-term in one side, a λ-term on the other, it must check if those are equal, so it needs an algorithm that does that. Simple as that. Am I missing something obvious here?

No, you're not missing anything. Obviously, I'm not arguing against having such an algorithm, it's a must and of course you want it to handle as many useful terms as possible. I'm only saying that it's not clear what terms, exactly, are useful and whether such terms can be replaced by some another ones that are simpler to deal with. So the prerequisites are not clear to me and this is why I'm trying to clarify them.  

> Agda's type-checker is fast

It's really not.

> For the same reason, it can't deal with function equality properly. For example, the program below:
> <...>
> Doesn't involve λ-encodings and doesn't crash Agda, but still fails to type-check as it refuses to reduce inside functions:

This was a design decision, not something inherent to Agda. Agda does reduce under lambdas. Consider this snippet:

```agda
caseNat : {A : Set} -> A -> (Nat -> A) -> Nat -> A
caseNat z f  zero    = z
caseNat z f (succ n) = f n

f : Nat -> Nat
f = caseNat zero (λ pred -> succ (succ pred))

g : Nat -> Nat
g = caseNat zero (λ pred -> f (succ pred))

main : Equal (Nat -> Nat) f g
main = equal
```

It type checks just fine, even though `f` and `g` are still functions and do the same thing as your original definitions. The only thing I changed there is abstracted pattern matching on the `Nat` argument out. It's not the lambda that blocks normalization in Agda, it's pattern matching. In fact, even those pattern-matching functions that have literally the same clauses and bodies are not considered equal by Agda, e.g. this:

```agda
f1 : Nat -> Nat
f1 zero        = zero
f1 (succ pred) = succ (succ pred)

f2 : Nat -> Nat
f2 zero        = zero
f2 (succ pred) = succ (succ pred)

main : Equal (Nat -> Nat) f1 f2
main = equal
```

also gives an error. Even this one gives an error:

```agda
f1 : Nat -> Nat
f1 = λ
  { zero        -> zero
  ; (succ pred) -> succ (succ pred)
  }

f2 : Nat -> Nat
f2 = λ
  { zero        -> zero
  ; (succ pred) -> succ (succ pred)
  }

main : Equal (Nat -> Nat) f1 f2
main = equal
```

and the error is a funny one:

```
(λ { zero → zero ; (succ pred) → succ (succ pred) }) x !=
(λ { zero → zero ; (succ pred) → succ (succ pred) }) x of type Nat
```

Agda intentionally refuses to consider these two syntactically equal things definitionally equal.

By no means is it impossible to tweak Agda a bit to accept this definition and your original one as well.

> Causes Agda to crash hopelessly. And it is the simplest recursive λ-encoding you can write down, it doesn't even involve self-types or induction.

Sure, Agda is not Formality and I've never argued that Formality should become Agda, that would be quite a silly thing to do. Not sure how comparison to Agda is related to the discussion at all, to be honest. I've only mentioned Agda once when I used it as a tool to quickly fake some pseudo-Formality in it.

> The point of this issue was to look for better ways to compare arbitrary λ-terms, since my algorithm is quite naive.

I talked with John a bit about equirecursion-vs-isorecursion and he referenced this issue, so I assumed continuing the discussion here would be a sensible thing to do. I can stop doing that or continue in a different issue.

**Comment by VictorTaelin** [comment]
Okay, I now understand what you're trying to do better and I don't disagree with your points at all. Also, sorry if I sounded a little bit combative, I was just trying to explain the problem.

> I'm also describing what problems identifying things with their encodings might cause. Is it the case that with One defined as a parameterized type (as opposed to an indexed one) One Bool and One Nat are the same?

Yes, I actually see those as equal. I'd like for you to elaborate why you consider it such a big problem though, I may be missing an important problem here.

> It's really not.

I meant for the cases presented, on which it doesn't get exponential while Formality does.

> It's not the lambda that blocks normalization in Agda, it's pattern matching. 

Yes, sorry, what is what I should've said. But actually there is no case expression preventing the `g` definition above from reducing to the same term as `f`, no? In any case I'm very sleepy and tired right now so I'll double check tomorrow.

> I talked with John a bit about equirecursion-vs-isorecursion and he referenced this issue, so I assumed continuing the discussion here would be a sensible thing to do. I can stop doing that or continue in a different issue.

I think we should close the issue and make two new issues, one specifically to explore an equality algorithm for arbitrary untyped λ-terms, and another to improve the practical equality of Formality in interesting subsets.

**Comment by effectfully** [comment]
> Yes, I actually see those as equal. I'd like for you to elaborate why you consider it such a big problem though, I may be missing an important problem here.

People use phantom types specifically to statically distinguish between types that have a common semantics and the same internal representation. Here is [one random post](https://ren.zone/articles/safe-money) about using phantom types for distinguishing between currencies. Everything there would break if the type checker accepted a `Dense "USD"` where a `Dense "EUR"` is expected.

Is it also the case that if you write an equivalent of Haskell's

```haskell
data USD = USD Int
data EUR = EUR Int
```

in Formality, then the type checker will not mind if you pass a `USD` where a `EUR` is expected? 

> I meant for the cases presented, on which it doesn't get exponential while Formality does.

Ah, ok. Anyway, Agda does a quick syntactic check and if it fails, then it just reduces things to whnf, checks equality, proceeds (I'm not actually aware of the details of implementation, so take it with a grain of salt). So it's not that what Agda has is somehow bound to Agda's theory. You could just as well implement an algorithm that checks equality of arguments, backtracks on failure, etc and Agda would certainly benefit from it. So I do not see at the moment whether requirements for your equality checking algorithm are any different from what Agda would also benefit from. Even regarding infinite terms, Agda also allows non-termination (locked under a pragma) and I did lie a few times to the type checker about a certain definition being `TERMINATING` when it was actually not (otherwise Agda would refuse to expand it).

> But actually there is no case expression preventing the g definition above from reducing to the same term as f, no?

You mean, in your original definitions? Agda [elaborates pattern matching to case trees](https://agda.readthedocs.io/en/latest/language/function-definitions.html#case-trees).

> I think we should close the issue and make two new issues, one specifically to explore an equality algorithm for arbitrary untyped λ-terms, and another to improve the practical equality of Formality in interesting subsets.

:+1:

**Comment by VictorTaelin** [comment]
Formality was refactored entirely. The new equality proposed by Gabriel is amazing and solves all those issues. It can be seen [here](https://github.com/moonad/Formality/blob/master/javascript/FormalityCore.js#L327). The main idea is that two terms are equal if they are identical (i.e., same computationally relevant string). If not, then we reduce to WHNF and check if the constructors are equal. If yes, then **we add the assumption that `a == b` to a map** and recurse on fields. If we ever reach `a == b` again, we return `true`. Adding `a == b` to a map is the catch that allows equal to terminate despite arbitrarily recursive terms and computations involved. Simple, elegant and clever. Thanks @gabriel-barrett and @johnchandlerburnham for your efforts!

**Comment by effectfully** [comment]
> The main idea is that two terms are equal if they are identical (i.e., same computationally relevant string). If not, then we reduce to WHNF and check if the constructors are equal. If yes, then we add the assumption that `a == b` to a map and recurse on fields. If we ever reach `a == b` again, we return true. Adding `a == b` to a map is the catch that allows equal to terminate despite arbitrarily recursive terms and computations involved. Simple, elegant and clever. 

That's the thing that I described above:

> But anyway, the reduce-to-whnf-check-proceed algorithm can be extended to handle such use cases: when you reduce `is_equal (One Unit) (One (Id Unit))` and reach `is_equal (One Unit) (One (Id Unit))`, i.e. the original expression, you get two cyclic finite graphs (one is formed by the reduction path of `One Unit` and the other one is formed by the reduction path of `One (Id Unit))`, and those graphs are of the same shape, so we conclude that they are the same without ever reducing `Id Unit` (basically we folded an infinite tree into a finite cyclic graph and this is exactly what supercompilers people do (well, the simplest thing that they do)).

Unfortunately, 

- a naive implementation has to make type checking undecidable. Does your type checker give up after a certain number of steps?
- a naive implementation handles some cases, but not the others
- since you're now dabbling in the supercompilation field, you might want to enjoy its other benefits (such as making `map f . map g` and `map (f . g)` definitionally equal, for example). Or might not as that is more computationally intense, but see the previous point

 I'll try to come up with a couple of test cases once I have some time.
