### ISSUE TITLE
Improve compilation of cases to Javascript 

### ISSUE THREAD

**Issue by Eloitor** [HigherOrderCO/Kind#68]
This has a recursive call inside each case

> toBrainFuck(p : List(Instruction)) : String
>   case p
>   | nil => nil(_)
>   | cons =>
>   case p.head as ins
>       | right => cons(_ '>', toBrainFuck(p.tail))
>       | left  => cons(_ '<', toBrainFuck(p.tail))
>       | inc   => cons(_ '+', toBrainFuck(p.tail))
>       | dec   => cons(_ '-', toBrainFuck(p.tail))
>       | write => cons(_ '.', toBrainFuck(p.tail))
>       | read  => cons(_ ',', toBrainFuck(p.tail))
>       | loop  => concat(_ concat(_ cons(_ '[' , toBrainFuck(ins.code)), "]"), toBrainFuck(p.tail))
> 

So, when compiled to JS, every case would recurse, being accidentally exponential.

A temporary solution:  insert `+ toBrainFuck : List(Instruction) -> String` inside `toBrainFuck`, below the second `case`.
This will pass the recursive calls linearly to each branches, preventing this problem from happening. it is also a very good practice in general, interaction nets like that style.

On the long term, we can make the JS compiler lazy by wrapping every value inside a `()=>...` closure

**Comment by VictorTaelin** [comment]
To elaborate, the current JS back-end evaluates all branches of a `case` expression, because those are compiled to raw function applications (`val(case_a, case_b, case_c, ...)`), which aren't evaluated lazily in JavaScript. This can be avoided by manually inserting `+ func : T` below the `case`, as suggested on the documentation. A more long-term solution would be to make the JS compiler lazy, or to make `-r` default to the upcoming Haskell compiler, which is lazy.

**Comment by VictorTaelin** [comment]
Formality was reworked entirely and the compiler is much smarter, but it still lacks laziness on cases. Must be added.

**Comment by VictorTaelin** [comment]
Fixed on https://github.com/moonad/Formality/commit/e314755ff7d7b39a1ec0fb76eeb9cdf2dc8cac20!
