### ISSUE TITLE
How to erase rewrites from the runtime?

### ISSUE THREAD

**Issue by VictorTaelin** [HigherOrderCO/Kind#88]
In Formality, the identity type and the rewrite (transp) operation are, like all other datatypes, implemented using self types:

```c
// The Equal datatype.
T Equal <A: Type> (a: A) ~ (b: A)
| to                     ~ (a);

// If a == b, then, P(a) implies P(b)
Equal.rewrite<A: Type, a: A, b: A, P: A -> Type>(e: Equal(A,a,b), x: P(a)): P(b)
  case e:
  | x;
  : P(e.b);
```

The problem is that, since, inside `Equal.rewrite`, `e` is used in a computational position, it appears at runtime. That means equality proofs and casts can't be completely erased from runtime as would be desired. How can this problem be avoided?

**Comment by atennapel** [comment]
I think in Coq there is a separate `Prop` universe for proof irrelevant (erasable) propositions. So maybe you could also have an universe for those, such that `Equal(A,a,b) : Prop`. I have no idea about the details of that though, it's still something I'm trying to learn myself.

Another approach would be primitive or user-defined rewrite rules, so that `Equal.rewrite(e, x) ~> x`. Though I guess that will make type preservation (aka subject reduction) fail.

Note that it's only type-safe to erase proofs if the type theory is consistent. Else I could just proof `A = B` with an infinite loop and then cast `A` to `B` freely (if the proof was erased). So the proof cannot be erased so that if you have an invalid proof `A = B` then at least you will get an infinite loop when you try to cast `A` to `B`.

See [this stackoverflow question](https://stackoverflow.com/questions/61930740/in-a-dependently-typed-programming-language-is-type-in-type-practical-for-progra/61933483#61933483) for a nice answer.
